name: CI

on:
  pull_request:
  push:
    branches:
      - "main"

concurrency:
  group: CI

jobs:
  test:
    name: Run tests & display/prepare coverage
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -e .
        working-directory: subdir

      - run: pytest
        working-directory: subdir

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@2b84cfb222691291ba358a586c13606f0a9c172c
        with:
          GITHUB_TOKEN: ${{ github.token }}
          ANNOTATE_MISSING_LINES: true
          ANNOTATION_TYPE: notice
          COVERAGE_PATH: subdir
          SUBPROJECT_ID: "my-great-project"

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v4
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action*.txt
